spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:devcamp
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /index.html
    groups-order: asc
  cache:
    disabled: true
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  file:
    name: logs/devcamp.log
  logback:
    rolling policy:
      max-file-size: 50MB
      max-history: 7
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log

jwt:
  secret:
    key: 7ZiE7JeF7JeQ7ISc7JuQ7ZWY64qU7KO864uI7Ja06rCc67Cc7J6Q66W87Jyh7ISx7ZWY6riw7JyE7ZW07YyA7Iqk7YyM66W07YOA7JeQ7ISc7KeE7ZaJ7ZWY64qU642w67iM7Lqg7ZSE

